platform :ios, '9.0'
use_frameworks!

target 'frame' do
    pod 'ObjectMapper'
    pod 'SwiftyJSON'
    pod 'Masonry'
    pod 'Alamofire'
    pod 'CryptoSwift'
    pod 'SQLite.swift'
    pod 'SwiftEventBus'
#    pod 'BaiduMapKit', '~>6.2.0'
    pod 'YBImageBrowser'
    pod 'Masonry'
    pod 'SwiftQRCode'
end
