platform :ios, '9.0'
use_frameworks!

target 'frame' do
    pod 'ObjectMapper'
    pod 'SwiftyJSON'
#    pod 'Moya'
    pod 'Alamofire'
    pod 'CryptoSwift'
    pod 'SQLite.swift'
    pod 'SwiftEventBus'
    pod 'BaiduMapKit'
    pod 'YBImageBrowser'
    pod 'Masonry'
end
